name: gen_iso
on:
  push:
  workflow_dispatch:
    inputs:
      password:
        description: 'Password for tc user'
        default: 'toor'
        required: false
      ip:
        description: 'Static IP address (leave empty for DHCP)'
        required: false
      netmask:
        description: 'Subnet mask'
        default: '255.255.255.0'
        required: false
      gateway:
        description: 'Default gateway'
        required: false
      nameserver:
        description: 'DNS server(s) (comma separated)'
        default: '8.8.8.8,1.1.1.1'
        required: false
      ssh_port:
        description: 'SSH port'
        default: '22'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pacakges
        run: |
          apt-get update
          apt-get -y install squashfs-tools cpio tar gzip genisoimage xorriso advancecomp p7zip-full
          apt-get clean

      - name: Run Script
        run: |
          PASSWORD="${{ github.event.inputs.password }}" \
          IP="${{ github.event.inputs.ip }}" \
          NETMASK="${{ github.event.inputs.netmask }}" \
          GATEWAY="${{ github.event.inputs.gateway }}" \
          NAMESERVER="${{ github.event.inputs.nameserver }}" \
          SSH_PORT="${{ github.event.inputs.ssh_port }}" \
          bash main.sh

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: tcl.iso
          path: /tmp/tcl.iso